# Post User
POST http://localhost:8000/api/user/
content-type: application/json

{
  "id":"cjld2cjxh0006qzrmn831i7rn",
  "firstName":"Ahzam",
  "lastName":"Ahmed",
  "email":"test6@test.com",
  "password":"Marvel-2001$"
}