### Post User
POST http://localhost:8000/api/user/
content-type: application/json

{
  "id":"cjld2cjxh0006qzrmn831i7rn",
  "firstName":"Ahzam",
  "lastName":"Ahmed",
  "email":"test6@test.com",
  "password":"Marvel-2001$"
}


### Login User
POST http://localhost:8000/api/login/
content-type: application/json

{
  "email":"test6@test.com",
  "password":"Marvel-2001$"
}


### Delete User
DELETE http://localhost:8000/api/delete?id=cjld2cjxh0006qzrmn831i7rn
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjamxkMmNqeGgwMDA2cXpybW44MzFpN3JuIiwiZW1haWwiOiJ0ZXN0NkB0ZXN0LmNvbSIsImlhdCI6MTY4ODA1NTc5NSwiZXhwIjoxNjg5NzgzNzk1fQ.1q3Y7bRtJdMGLXMBVBGJguFO16SNra0ZvRyMWjAirGI


### Verify User
GET http://localhost:8000/api/verify
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjamxkMmNqeGgwMDA2cXpybW44MzFpN3JuIiwiZW1haWwiOiJ0ZXN0NkB0ZXN0LmNvbSIsImlhdCI6MTY4ODA1NTc5NSwiZXhwIjoxNjg5NzgzNzk1fQ.1q3Y7bRtJdMGLXMBVBGJguFO16SNra0ZvRyMWjAirGI


### Issue Token
GET http://localhost:8000/api/issuetoken
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjamxkMmNqeGgwMDA2cXpybW44MzFpN3JuIiwiZW1haWwiOiJ0ZXN0NkB0ZXN0LmNvbSIsImlhdCI6MTY4NDM0NzU5OSwiZXhwIjoxNjg2MDc1NTk5fQ.aYcHVQKNMNNGTtZZJI8YTijmGFQtproToOHF5axqIJI


### Change Password
PATCH http://localhost:8000/api/changepassword
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjamxkMmNqeGgwMDA2cXpybW44MzFpN3JuIiwiZW1haWwiOiJ0ZXN0NkB0ZXN0LmNvbSIsImlhdCI6MTY4NDM0NzU5OSwiZXhwIjoxNjg2MDc1NTk5fQ.aYcHVQKNMNNGTtZZJI8YTijmGFQtproToOHF5axqIJI

{
  "oldPassword":"Marvel-2001$",
  "newPassword":"Marvel-2001$new"
}
